In [4]:
import numpy as np


vector = np.random.randint(1, 21, size=15)


print('Random Vector:',vector)
reshaped_array = vector.reshape(3, 5)
print('\nReshaped array:\n', reshaped_array)
print('\nReshaped array shape:',reshaped_array.shape)
reshaped_array[np.arange(reshaped_array.shape[0]), reshaped_array.argmax(axis=1)] = 0
print('\nReplacing max element in each row:\n',reshaped_array)


Random Vector: [12 17  1  9  4 12 11 15  8 13 10  4  6 12 15]

Reshaped array:
 [[12 17  1  9  4]
 [12 11 15  8 13]
 [10  4  6 12 15]]

Reshaped array shape: (3, 5)

Replacing max element in each row:
 [[12  0  1  9  4]
 [12 11  0  8 13]
 [10  4  6 12  0]]


In [5]:
import numpy as np

# 2 dimensional array of size 4x3 with 4-byte integer elements
array_2d = np.zeros((4, 3), dtype=np.int32)

# shape, type, and data type of the array
array_shape = array_2d.shape
array_type = type(array_2d)
array_dtype = array_2d.dtype

# Print the results
print("Array:\n", array_2d)
print("\nShape:", array_shape)
print("\nType:", array_type)
print("\nData type:", array_dtype)


Array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

Shape: (4, 3)

Type: <class 'numpy.ndarray'>

Data type: int32


In [6]:
import numpy as np
# defining the square array
arr = np.array([[3, -2], [1, 0]])

# compute the eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(arr)

# print the eigenvalues and right eigenvectors
print("Eigenvalues:", eigenvalues)
print("\nRight eigenvectors:\n",eigenvectors)

Eigenvalues: [2. 1.]

Right eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [7]:
import numpy as np

arr = np.array([[0, 1, 2], [3, 4, 5]])
sum = np.trace(arr)
print("Sum of diagonal elements is:", sum)

Sum of diagonal elements is: 4


In [8]:
import numpy as np

# original array
arr = np.array([[1, 2], [3, 4], [5, 6]])

# reshape to 3x2
arr_3x2 = arr.reshape(3, 2)

# reshape to 2x3
arr_2x3 = arr.reshape(2, 3)

print("Original array:\n", arr_3x2)
print("Modified array:\n", arr_2x3)

Original array:
 [[1 2]
 [3 4]
 [5 6]]
Modified array:
 [[1 2 3]
 [4 5 6]]
